version: '3.4'

services:
  searchengineapi:
    image: ${DOCKER_REGISTRY-}searchengineapi
    container_name: searchengineapi
    build:
      context: .
      dockerfile: SearchEngineAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  searchengine_database:
    image: postgres:latest
    container_name: searchengine_database
    environment:
      - POSTGRES_DB=WebSearchArchive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/searchengine-db:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - searchengine_network
  
  searchengine_cache:
    image: redis:latest
    container_name: searchengine_cache
    restart: always
    ports:
      - "6378:6379"
    networks:
      - searchengine_network

networks:
  searchengine_network:
    driver: bridge